### ISSUE TITLE
strange behavior with high load

### ISSUE THREAD

**Issue by benjamin-dreux** [xmlet/HtmlFlow#116]
In the process of writing an app I was wondering how my app was behaving with load way above what i'm expecting anytime soon.

I'm expexting to see  a higher rate of error, but what is strange to me is the way my template is failing.

Running the same page with only one request, no error message.
But running 1000 request concurrently I'm starting to see error message like this

```
java.lang.IllegalStateException: Cannot add attributes after!!!
	at htmlflow.visitor.HtmlVisitor.visitAttribute(HtmlVisitor.java:179) ~[htmlflow-4.3.jar:na]
	at org.xmlet.htmlapifaster.ElementVisitor.visitAttributeHref(ElementVisitor.java:1409) ~[htmlApiFaster-1.0.15.jar:na]
	at org.xmlet.htmlapifaster.A.attrHref(A.java:50) ~[htmlApiFaster-1.0.15.jar:na]
	at get.simple.today.lender.file.FileShowView.lambda$template$5(FileShowView.java:142) ~[classes/:na]
	at htmlflow.continuations.HtmlContinuationSyncDynamic.emitHtml(HtmlContinuationSyncDynamic.java:70) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:26) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.continuations.HtmlContinuationSync.execute(HtmlContinuationSync.java:28) ~[htmlflow-4.3.jar:na]
	at htmlflow.visitor.HtmlViewVisitor.resolve(HtmlViewVisitor.java:59) ~[htmlflow-4.3.jar:na]
	at htmlflow.HtmlView.render(HtmlView.java:114) ~[htmlflow-4.3.jar:na]
	at get.simple.today.lender.file.FileController.showFile(FileController.java:166) ~[classes/:na]
...
```
Here is what my view looks like
```
                      .form()
                        .attrClass("form")
                        .attrMethod(EnumMethodType.POST)
                        .<File>dynamic((form, model) -> form.attrAction("/file/%s/edit".formatted(model.publicId())))
                        .div().attrClass("field")
                            .label().attrClass("label")
                                .text("File id")
                            .__()
                            .div()
                                .attrClass("control")
                                .input()
                                    .attrType(EnumTypeInputType.TEXT)
                                    .attrClass("input")
                                    .attrReadonly(true)
                                    .<File>dynamic((input, model) -> input.attrValue(model.publicId())) 
                                .__()
                            .__()
                        .__()
```

Is there something that could be done diffrently in my view to push my error rate still further ?

**Comment by benjamin-dreux** [comment]
By commenting every dynamic block, the errors disappears.

**Comment by benjamin-dreux** [comment]
I should add that I use the following script to run this testing

```
# requires
# brew install vegeta
# brew install rs/tap/jplot
# brew install rs/tap/jaggr


echo "GET http://localhost:8080/files/00001" | \
vegeta attack -duration=1m  -rate 1000| \
vegeta encode | \
jaggr @count=rps \
        hist\[100,200,300,400,500\]:code \
        p25,p50,p95:latency \
        sum:bytes_in \
        sum:bytes_out | \
jplot rps+code.hist.100+code.hist.200+code.hist.300+code.hist.400+code.hist.500 \
        latency.p95+latency.p50+latency.p25 \
        bytes_in.sum+bytes_out.sum
```

**Comment by fmcarvalho** [comment]
Assuming that you are using an HtmlView, did you set the parallel property to true?

**Comment by benjamin-dreux** [comment]
You are right, I'm using HtmlView with a layout as describe in the documentation

```
HtmlFlow.view(page -> Layout.template(page, content));
```

About the parallel property, do you mean `theadSafe` on `HtmlFlow.view` ?
If that is what you mean HtmlFlow.view doesn't have a public signature that allow access to it.

**Comment by fmcarvalho** [comment]
Yes, it has. It is described here: https://htmlflow.org/features#core-concepts

All configurations are accessible through a fluent API. Example: 
```java
var view =  HtmlFlow
   .view(page -> page.html().body().div().table()...)
   .setIndent(false)
   .threadSafe()
view.render(...)
```

You may chain methods calls in any order.

Note, an `HtmlView` is **immutable** and always return a new view. Thus next sample will **not have the desired behaviour**.
```java
var view =  HtmlFlow.view(page -> page.html().body().div().table()...)
view.threadSafe() // DOES NOT CHANGE the object pointed by the view variable
view.render(...)  // view still refer a non thread safe view
```

**Comment by benjamin-dreux** [comment]
ohh, my bad i didn't get it at first.

But i'm wondering why didn't you decided to make it thread safe by default ?
Is there a perfomance penalty ??

**Comment by fmcarvalho** [comment]
Yes there is a a perfomance penalty. In that case, it must use TLS to get the correct rendering context.

**Comment by benjamin-dreux** [comment]
I assume you mean thread local state

have you already thought about Java 21 and virtual thread and what impact this could have on htmlflow ?

**Comment by fmcarvalho** [comment]
Yes, I have.

In meanwhile I assume this potential issue is solved with the use of `threadSafe()` and I will close this issue.
